import oracledb

# Oracle DB connection
conn = oracledb.connect(user="student", password="apelix", dsn="localhost:1521/FREEPDB1")
cursor = conn.cursor()

# Create a simple knowledge table
cursor.execute("""
CREATE TABLE knowledge (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content CLOB
)
""")

# Insert some knowledge examples
texts = [
    "Python is a high-level programming language.",
    "LangChain is a framework for building LLM-powered applications.",
    "Ollama provides embeddings and LLM APIs for AI tasks.",
    "Oracle Database can store structured and unstructured data."
]

for text in texts:
    cursor.execute("INSERT INTO knowledge (content) VALUES (:1)", [text])

conn.commit()
print("Knowledge table ready.")
cursor.close()
conn.close()
